Models/party.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LANREG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class party
    {
        public party()
        {
            this.seat_user = new HashSet<seat_user>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string paypal { get; set; }
        public Nullable<int> layout_id { get; set; }
        public int org_id { get; set; }
        public string party_url { get; set; }
        public System.DateTime date_time_start { get; set; }
        public System.DateTime date_time_end { get; set; }
        public string location { get; set; }
    
        public virtual layout layout { get; set; }
        public virtual organization organization { get; set; }
        public virtual ICollection<seat_user> seat_user { get; set; }
    }
}

Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using LANREG.Models;

namespace LANREG.Controllers {
    public class LayoutController : _BaseControllerClass {

        //
		// GET: /{org_url}/Event/{party_url}/Seating/

		public ActionResult Details(string org_url, string party_url) {
			int party_id;
			// TODO: refactor this into global DAL?
			if (!int.TryParse(party_url, out party_id)) {
				party_id = (from prty in db.parties
							where prty.party_url == party_url
							select prty).Single().id;
			}

			SelectSeatingModel model = new SelectSeatingModel();
			model.tables = (from tbl in db.tables
							join prty in db.parties on tbl.layoutID equals prty.layout_id
							where prty.id == party_id
							select tbl).ToList();
			model.currUser = (from usr in db.users
							  where usr.id == 1
							  select usr).Single();
			// TODO: determine layoutID based on the partyID! (active layout)
			model.layoutID = 1;
			model.partyID = party_id;
			return View(model);
		}

        //
        // GET: /Layout/Create

        public ActionResult Create()
        {
			//TODO: Make this only currently logged in user's orgs, and set the default
			// selection to the user's a)referring or b)most active org.
			ViewBag.userOrgsOwnedDDL = new SelectList(db.organizations, "id", "name");
			ViewBag.tableLengthDDL = populateNumList(3, 20, 8);
			ViewBag.tableWidthDDL = populateNumList(1, 2, 2);
			ViewBag.tableOrientationDDL = populateTableOrientation();
			ViewBag.tableStepDDL = populateStep(0);
			ViewBag.seatStepDDL = populateStep(1);
			//TODO: load current user's orgs/layouts and allow edit upon selection?
			ViewBag.currentLayouts = db.layouts.Include(l => l.organization).ToList();

            return View();
        }

        //
        // POST: /Layout/Create

        [HttpPost]
        public bool Create(string jsonData) {
			try {
				if (jsonData == null)
					return false;
				SaveLayoutModel slm;
				JavaScriptSerializer jss = new JavaScriptSerializer();
				slm = jss.Deserialize<SaveLayoutModel>(jsonData);

				int i, numSeats = 0;
				string tableStep, seatStep;

				tableStep = setStep(slm.tableStep);
				seatStep = setStep(slm.seatStep);

				// Create a new layout in the db
				layout lo = new layout {
					name = slm.name,
					numSeats = 0,
					org_id = slm.orgID,
					shared = false
				};
				db.layouts.Add(lo);
				db.SaveChanges();

				// Create all tables and put them in the db
				foreach (table tbl in slm.tables) {
					tbl.layoutID = lo.id;
					tbl.name = tableStep;
					db.tables.Add(tbl);
					tableStep = incrementStep(tableStep);
				}
				db.SaveChanges();

				// Get all tables back out
				var query = (from tbl in db.tables
							 where tbl.layoutID == lo.id
							 select tbl).ToList();

				// Create all of the seats for each table
				foreach (table tbl in query) {
					for (i = 1; i <= tbl.length * tbl.width; i++) {
						seat st = new seat {
							name = seatStep,
							tableID = tbl.id,
							cost = Convert.ToInt32(slm.seatCost)
						};
						db.seats.Add(st);
						seatStep = incrementStep(seatStep);
						numSeats++;
					}
					seatStep = setStep(slm.seatStep);
				}

				lo.numSeats = numSeats;
				db.SaveChanges();
			}
			catch (Exception e) {
				return false;
			}

            return true;
        }

        //
        // GET: /Layout/Edit/5

        public ActionResult Edit(int id = 0)
        {
            layout layout = db.layouts.Find(id);
            if (layout == null)
            {
                return HttpNotFound();
            }
            ViewBag.org_id = new SelectList(db.organizations, "id", "name", layout.org_id);
            return View(layout);
        }

        //
        // POST: /Layout/Edit/5

        [HttpPost]
        public ActionResult Edit(layout layout)
        {
            if (ModelState.IsValid)
            {
                db.Entry(layout).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.org_id = new SelectList(db.organizations, "id", "name", layout.org_id);
            return View(layout);
        }

        //
        // GET: /Layout/Delete/5

        public ActionResult Delete(int id = 0)
        {
            layout layout = db.layouts.Find(id);
            if (layout == null)
            {
                return HttpNotFound();
            }
            return View(layout);
        }

        //
        // POST: /Layout/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            layout layout = db.layouts.Find(id);
            db.layouts.Remove(layout);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
		
		/* HELPER FUNCTIONS */

		private List<SelectListItem> populateNumList(int first, int last, int selectedValue) {
			List<SelectListItem> newList = new List<SelectListItem>();
			int zeroDiff = first;
			for (int i = first; i < (last + 1); i++) {
				SelectListItem sli = new SelectListItem {
						Text = Convert.ToString(i),
						Value = Convert.ToString(i - zeroDiff)
					};
				if (selectedValue == i) {
					sli.Selected = true;
				}
				newList.Add(sli);					
			}
			return newList;
		}

		private List<SelectListItem> populateTableOrientation() {
			List<SelectListItem> newList = new List<SelectListItem>();
			newList.Add(new SelectListItem { Text = "Vertical", Value = "0" });
			newList.Add(new SelectListItem { Text = "Horizontal", Value = "1" });
			return newList;
		}

		private List<SelectListItem> populateStep(int selectedIndex) {
			List<SelectListItem> newList = new List<SelectListItem>();
			newList.Add(new SelectListItem { Text = "Alpha (A-Z)", Value = "0" });
			newList.Add(new SelectListItem { Text = "Numerical (1-#)", Value = "1" });
			newList[selectedIndex].Selected = true;
			return newList;
		}

		private string setStep(int index) {
			// TODO: Error checking for wrong numbers
			switch (index) {
				case 0:
					return "A"; // A -> Z  , TODO: Account for past Z?
				case 1:
					return "1"; // Numerical
			}
			return "";
		}

		protected string incrementStep(string stepValue) {
			// Attempt to convert stepValue to integer format
			int myNum;
			if (int.TryParse(stepValue, out myNum)) {
				myNum++;
				return Convert.ToString(myNum);
			}
			// Attempt to convert to character format
			char myChar;
			if (char.TryParse(stepValue, out myChar)) {
				myChar++;
				return Convert.ToString(myChar);
			}
			return "";
		}
    }
}

Controllers/PartyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LANREG.Models;

namespace LANREG.Controllers {
    public class PartyController : _BaseControllerClass {

        //
		// GET: /Events

        public ActionResult Index() {
			return View(db.parties.ToList());
        }

        //
        // GET: /{org_url}/Event/{party_url}

        public ActionResult Details(string org_url, string party_url) {
			int party_id;
			// TODO: refactor this into global DAL?
			if (!int.TryParse(party_url, out party_id)) {
				party_id = (from prty in db.parties
							where prty.party_url == party_url
							select prty).Single().id;
			}
            party party = db.parties.Find(party_id);
            if (party == null) {
                return HttpNotFound();
            }
            return View(party);
        }

        //
        // GET: /Create/Party

        public ActionResult Create() {
            ViewBag.layoutID = new SelectList(db.layouts, "id", "name");
            ViewBag.org_id = new SelectList(db.organizations, "id", "name");
            return View();
        }

        //
        // POST: /Create/Party

        [HttpPost]
        public ActionResult Create(party party) {
            if (ModelState.IsValid) {
                db.parties.Add(party);
                db.SaveChanges();
				return RedirectToAction("Details", new { party_url = party.party_url });
            }

            ViewBag.layoutID = new SelectList(db.layouts, "id", "name", party.layout_id);
            ViewBag.org_id = new SelectList(db.organizations, "id", "name", party.org_id);
            return View(party);
        }

        //
        // GET: /Party/Edit/5

        public ActionResult Edit(int id = 0)
        {
            party party = db.parties.Find(id);
            if (party == null)
            {
                return HttpNotFound();
            }
            ViewBag.layoutID = new SelectList(db.layouts, "id", "name", party.layout_id);
            ViewBag.org_id = new SelectList(db.organizations, "id", "name", party.org_id);
            return View(party);
        }

        //
        // POST: /Party/Edit/5

        [HttpPost]
        public ActionResult Edit(party party)
        {
            if (ModelState.IsValid)
            {
                db.Entry(party).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.layoutID = new SelectList(db.layouts, "id", "name", party.layout_id);
            ViewBag.org_id = new SelectList(db.organizations, "id", "name", party.org_id);
            return View(party);
        }

        //
        // GET: /Party/Delete/5

        public ActionResult Delete(int id = 0)
        {
            party party = db.parties.Find(id);
            if (party == null)
            {
                return HttpNotFound();
            }
            return View(party);
        }

        //
        // POST: /Party/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            party party = db.parties.Find(id);
            db.parties.Remove(party);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

/* TODO: REMOVE
 * OLD CODE:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LANREG.Models;

namespace LANREG.Controllers
{
    public class EventController : Controller
    {
		LANRegistrationEntities lanDB = new LANRegistrationEntities();

		//GET /Event/?partyid
        public ActionResult Index(int partyID)
        {
			return View(getPartyFromID(partyID));
        }
		
		//POST: /Event/Create
		[HttpPost]
		public ActionResult Create(EventModel em, int partyid) {
			if(Model.IsValid)
				return Content("Hello");
			else
				return Content("Bad Data");
		}

		public ActionResult Seating(int partyID)
		{
			ViewBag.User = getSessionUser();
			return View(getPartyFromID(partyID));
		}

		public ActionResult Pay(int partyID)
		{
			return View();
		}

		private party getPartyFromID(int partyID)
		{
			return (from prty in lanDB.parties
					where prty.id == partyID
					select prty).Single();
		}

		private user getSessionUser()
		{
			if (Session["user"] != null) {
				return (user)Session["user"];
			} else {
				return new user();
			}
		}
    }
}
 */

Controllers/SeatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LANREG.Models;

namespace LANREG.Controllers {
    public class SeatingController : Controller {

		private LANRegistrationEntities db = new LANRegistrationEntities();

        // GET: /Event/{party_url}/Seating/

        public ActionResult Index(string party_url) {
			int party_id;
			// TODO: refactor this into global DAL?
			if (!int.TryParse(party_url, out party_id)) {
				party_id = (from prty in db.parties
							where prty.party_url == party_url
							select prty).Single().id;
			}
			
			SeatingSelectionModel model = new SeatingSelectionModel();
			model.tables = (from tbl in db.tables
							join prty in db.parties on tbl.layoutID equals prty.layoutID
							where prty.id == party_id
							select tbl).ToList();
			model.currUser = (from usr in db.users
							  where usr.id == 1
							  select usr).Single();
			// TODO: determine layoutID based on the partyID! (active layout)
			model.layoutID = 1;
			model.partyID = party_id;
            return View(model);
        }

		/* SHOULD THESE JUST BE IN LAYOUT?  SEATING IS DIFF RIGHT?
		// GET: /Seating/Edit/5

		public ActionResult Edit(int layoutID) {

		}

		// GET: /Seating/Create

		public ActionResult Create() {

		} */
    }
}

Views/Party/Create.cshtml
@model LANREG.Models.party

@{
    ViewBag.Title = "New Event";
}

<h2>New Event</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>party</legend>

        <div class="editor-label">
            Event Name
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </div>

        <div class="editor-label">
            Desired URL (www.lanreg.com/{url})
        </div>
		<div class="editor-field">
            @Html.EditorFor(model => model.party_url)
            @Html.ValidationMessageFor(model => model.party_url)
        </div>

		<div class="editor-label">
            Paypal Email
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.paypal)
            @Html.ValidationMessageFor(model => model.paypal)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Party/Delete.cshtml
@model LANREG.Models.party

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>party</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.paypal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.paypal)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.layout.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.layout.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.organization.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.organization.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.party_url)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.party_url)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/Party/Details.cshtml
@model LANREG.Models.party

@{
    ViewBag.Title = "Details";
}

@section featured {
	<section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@Html.DisplayFor(model => model.name).</h1>
			</hgroup>
			<p>
				@Html.DisplayFor(model => model.location)
			</p>
        </div>
		<div class="group-nav" style="float:right">
			@Html.ActionLink("// Seating", "Details", "Layout", null, new { org_url = Model.organization.org_url, party_url = Model.party_url } )
		</div>
    </section>
	
}

			

<fieldset>
    <legend>party</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.paypal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.paypal)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.layout.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.layout.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.organization.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.organization.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.party_url)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.party_url)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<br />
<p>
	@Html.ActionLink("GO TO THE SEATING!", "Index", "Seating")
</p>

Views/Party/Edit.cshtml
@model LANREG.Models.party

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>party</legend>

        @Html.HiddenFor(model => model.id)

        <div class="editor-label">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.paypal)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.paypal)
            @Html.ValidationMessageFor(model => model.paypal)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.layoutID, "layout")
        </div>
        <div class="editor-field">
            @Html.DropDownList("layoutID", String.Empty)
            @Html.ValidationMessageFor(model => model.layoutID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.org_id, "organization")
        </div>
        <div class="editor-field">
            @Html.DropDownList("org_id", String.Empty)
            @Html.ValidationMessageFor(model => model.org_id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.party_url)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.party_url)
            @Html.ValidationMessageFor(model => model.party_url)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Party/Index.cshtml
@model IEnumerable<LANREG.Models.party>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.paypal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.layout.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.organization.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.party_url)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.paypal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.layout.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.organization.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.party_url)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>